CREATE TABLE [dbo].[ArticleTag](
	[ArticleId] [int] NOT NULL,
	[Tag] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_ArticleTag] PRIMARY KEY NONCLUSTERED 
(
	[ArticleId] ASC,
	[Tag] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE CLUSTERED INDEX [IX_ArticleTag_Tag] ON [dbo].[ArticleTag] 
(
	[Tag] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ArticleTag]  WITH CHECK ADD  CONSTRAINT [FK_ArticleTag_Article] FOREIGN KEY([ArticleId])
REFERENCES [dbo].[Article] ([ArticleId])
GO

ALTER TABLE [dbo].[ArticleTag] CHECK CONSTRAINT [FK_ArticleTag_Article]
GO

ALTER TABLE [dbo].[ArticleTag]  WITH CHECK ADD  CONSTRAINT [CK_ArticleTag_TagLength] CHECK  ((len([Tag])>=(3)))
GO

ALTER TABLE [dbo].[ArticleTag] CHECK CONSTRAINT [CK_ArticleTag_TagLength]
GO